# Generated by Django 5.2.5 on 2025-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosdosistema',
            name='cargo',
            field=models.CharField(default='Sem cargo', max_length=100),
        ),
        migrations.AddField(
            model_name='usuariosdosistema',
            name='nivel_de_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario normal')], default='usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='usuariosdosistema',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
