# Generated by Django 5.2.5 on 2025-08-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_registrada', models.DateField(auto_now_add=True)),
                ('hora_registrada', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidosDeCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pedido', models.IntegerField()),
                ('empresa', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('requisicao', models.TextField()),
                ('resposta', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondido', 'Respondido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_req_logs.emails')),
            ],
        ),
    ]
