# Generated by Django 5.2.5 on 2025-08-21 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_req_logs', '0002_rename_pedidos_de_cotacao_pedidosdecotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='date_registrada',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emails',
            name='hora_registrada',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
