# Generated by Django 5.2.5 on 2025-08-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_req_logs', '0003_emails_date_registrada_emails_hora_registrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email',
            field=models.EmailField(default=1996, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
